### ISSUE TITLE
tox fails, can't find setup.py

### ISSUE THREAD

**Issue by joeydumont** [briggySmalls/cookiecutter-pypackage#21]
* Date you used Cookiecutter PyPackage: 2020-05-28
* Cookiecutter version used, if any: 1.6.0
* Python version, if any: 3.7
* tox version: 3.14.0
* Operating System: RHEL7

### Description

I created a new project with this cookiecutter template, and ran `tox` immediately afterward on the generated project. This failed with

```
$ tox
ERROR: No setup.py file found. The expected location is:
  <redacted>/setup.py
You can
  1. Create one:
     https://packaging.python.org/tutorials/distributing-packages/#setup-py
  2. Configure tox to avoid running sdist:
     https://tox.readthedocs.io/en/latest/example/general.html#avoiding-expensive-sdist
```

**Comment by briggySmalls** [comment]
Thanks for your bug report. I'm sorry about that! I just underwent quite a big conversion from using `pipenv` to `poetry` and I am still fixing bugs here and there.

I'm looking into this one now!

**Comment by briggySmalls** [comment]
Hi there 👋 

I think I've found the issue and will be merging the fix soon.

If you want to get your already-generated package to work you can look at PR #22 for the changes you'll need. They are quite small and _mainly_ follow the [poetry FAQ](https://python-poetry.org/docs/faq/#is-tox-supported) on the topic that I should have read by now!

Thanks again for your issue. I hope you find the project useful!

**Comment by joeydumont** [comment]
Thanks, I implemented the fix manually in my project and it worked!

**Comment by briggySmalls** [comment]
Sensational! 🎆
