### ISSUE TITLE
bitbucket support

### ISSUE THREAD

**Issue by troywweber7** [briggySmalls/cookiecutter-pypackage#7]
* Date you used Cookiecutter PyPackage: `2020-01-04`
* Cookiecutter version used, if any: `1.7.0`
* Python version, if any: `3.7`
* Operating System: `Ubuntu 18.04`

### Description

Ran cookiecutter and it asks for `github_username`. I do have a github, but I use bitbucket a lot more. Does this have support for bitbucket? How hard would it be to add support?

### What I Did

```
cookiecutter gh:briggySmalls/cookiecutter-pypackage
```

**Comment by briggySmalls** [comment]
Hello, Thanks for your issue.

The `github_username` is a feature from the original cookiecutter, so this questiong _might_ be best answered there. If you look in the repo, the `github_username` is mostly used to populate text in documentation:
- README.rst
- installation.rst
- CONTRIBUTING.rst

These tend to say that the repo is hosted at Github. References a `/issues` slug relative to the repo, etc. I'm not sure what these URLs would be on Bitbucket.

The cookiecutter _could_ be made configurable and substitute in the correct URLS depending on platform, but I think that might make the project more complicated than it need be. It might be better to make a bitbucket fork. It might be sensible for this cookiecutter project to better advertise that it is designed to be used for platforms on Github...

**Comment by troywweber7** [comment]
Thanks! I think I'm just going to go with GitHub for now because it's been a while since I've done Python and I'm most interested in making sure I'm programming in an isolated environment than that I can have private repos. Your explanation helps, though. I come from the world of Typescript / node.js / npm and there are just some language constructs that I miss having in Python. But in Python there are some isolation / collaboration pieces I'm trying to fill in the gaps for. This scaffold project seems like it addresses many of those.
