### ISSUE TITLE
template inconsistencies (author)

### ISSUE THREAD

**Issue by troywweber7** [briggySmalls/cookiecutter-pypackage#8]
* Date you used Cookiecutter PyPackage: `2020-01-04`
* Cookiecutter version used, if any: `1.7.0`
* Python version, if any: `3.7`
* Operating System: `Ubuntu 18.04`

### Description

This is minor, and maybe intentional, but in your `README.rst` it credits the original author instead of your fork. Perhaps both should be mentioned? I may also comment on this issue as time goes on if I find any other inconsistencies that you might have overlooked.

Let me know if this is not helpful. My intent is to be helpful and give credit where credit is due. Like what I see so far.

### What I Did

Ran cookiecutter

**Comment by briggySmalls** [comment]
Hello.

Yes this is very helpful, thanks! If you are using the project and you notice anything else it would be great to be notified of them.

Thanks very much, and I'm glad someone's getting some use out of this fork :)

**Comment by briggySmalls** [comment]
Note-to-self: this is the _generated_ README.rst that contains the original author
