### ISSUE TITLE
Move package management to Poetry 

### ISSUE THREAD

**Issue by rasoolsomji** [briggySmalls/cookiecutter-pypackage#9]
As little as I like running after the new hotness, I suspect that [Poetry](https://github.com/python-poetry/poetry/blob/master/README.md) is replacing pipenv as the defacto package manager for python. 
It recently released a stable 1.0 version, and seems to be well liked by the hackernews hivemind. 
Something to consider maybe

**Comment by briggySmalls** [comment]
Yeah I hear you. I also kinda hate pipenv. I'm not sure when I'll get around to this, but I agree.

**Comment by briggySmalls** [comment]
Ok. we've moved to poetry at work. I feel mentally prepared for this change...
